version: '3.8'

services:
  app:
    build: .
    container_name: notification-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - redis
    environment:
      QUEUE_CONNECTION: redis
      REDIS_HOST: redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
